### ISSUE TITLE
Upgrade plugin for Craft 4

### ISSUE THREAD

**Issue by jcdarwin** [pierrestoffe/craft-language-redirector#19]
Just wondering if there's any plans to upgrade the craft-language-redirector plugin for Craft 4?

https://craftcms.com/docs/4.x/extend/updating-plugins.html#high-level-notes

**Comment by pierrestoffe** [comment]
@jcdarwin Sure, the plugin was just updated to support Craft CMS 4.x, see [release 2.0.0](https://github.com/pierrestoffe/craft-language-redirector/releases/tag/2.0.0)
