### ISSUE TITLE
Redirect from home page to language URL?

### ISSUE THREAD

**Issue by petehjfd** [pierrestoffe/craft-language-redirector#21]
Hi, I may be misunderstanding how this should work, but...

We have two languages on our site:

https://www.example.com/en/
https://www.example.com/ar/

When a user visits https://www.example.com/ we would like them to be redirected to one of the two languages.  For example, if my browser language is English, I should be redirected from https://www.example.com/ to https://www.example.com/en/.

Is this how it is supposed to work?  If so, can you suggest what I might be doing wrong?  If not, do you have any suggestions for the best way to acheive this?

Thanks

**Comment by pierrestoffe** [comment]
@petehjfd If your two Sites are referencing the /en and /ar URL segments, the plugin will redirect from /en to /ar and vice-versa if everything is set up correctly. It may not pick up the / root URL **if that URL isn't a Craft-based route** though, so in that case you should also add a 301 or 302 redirection from / to /en for example (I personally do that in the nginx configuration), and from there the plugin will take over and do its job.

I have this working that same way on 1 or 2 websites, but let me know if you're having difficulties making it work properly. Please share a full representation of the Sites structure of your website + the content of your language-redirector.php file in that case.

**Comment by petehjfd** [comment]
Thanks @pierrestoffe.  The /en to /ar (and vice versa) redirects are working fine, so that's all good.  We have a Section setup for the homepage:

![Screenshot 2022-12-05 at 15 46](https://user-images.githubusercontent.com/29060670/205680503-11f3c312-e5b9-43f5-987c-99f6955be4cc.png)

Would this not count as a Craft-based route?

If not, we'll setup a redirect as you suggest.

Here's our language-redirector.php file:

```php
<?php
return [
    'languages' => [
      'en' => 'en',
      'ar' => 'ar'
    ],
    'queryParameterName' => 'lang',
    'sessionKeyName' => 'lang',
    'redirectUsersWithCpAccess' => true,
    'canRedirect' => true,
    'defaultEntryId' => null,
];
```

Here's our site settings:

![Screenshot 2022-12-05 at 15 46](https://user-images.githubusercontent.com/29060670/205680605-efd5c10f-b439-44a8-8f79-96e6c564bcc5.png)


Thanks

**Comment by pierrestoffe** [comment]
@petehjfd If I'm not mistaken the routes to your homepage are /en and /ar in the Sites section, but you don't have any Site referencing / only. If I'm not mistaken this means that / isn't a real Craft route… or at least not the kind of route that the plugin is listening to.

In any case the plugin unfortunately won't be listening to the / route in that scenario and I confirm that you'll have to setup the initial redirection manually.

I hope that this fully answers your question!

**Comment by petehjfd** [comment]
OK no worries, we'll setup the redirect manually.  Thanks for your help!
