### ISSUE TITLE
Detected Language Variable

### ISSUE THREAD

**Issue by stephanwergles** [pierrestoffe/craft-language-redirector#24]
Hi Pierre, 

I have a specific request that I believe could enhance the plugin's user experience. Instead of automatically redirecting users to the detected language, I'd like to display a banner that offers the option to switch languages. This banner would show the detected/preferred language and include a button for users who choose to make the switch. 

**Suggested backend logic:** 
1. Adding a method within Twig templates to detecting that a better match for the current user exists
2. Making the information of the suggested language available within Twig templates

Could this feature be integrated into your existing plugin? I believe it could greatly improve user engagement by providing them with a choice rather than redirecting them automatically.

Thanks for your excellent work.

**Comment by pierrestoffe** [comment]
Hi @stephanwergles

This is a great idea and has just been added to the plugin, in release [3.1.0](https://github.com/pierrestoffe/craft-language-redirector/releases/tag/3.1.0) (requires Craft CMS 5). You can install this release by updating your list of dependencies in your composer.json file and running `composer update`.

A basic Twig example has been added in [the Wiki](https://github.com/pierrestoffe/craft-language-redirector/wiki/Language-suggestion) to help you set it up in your project.
I have only been able to test it in two different Sites structures so let me know if you're encountering issues.

**Comment by stephanwergles** [comment]
hi @pierrestoffe, 

wow that was a quick one :)

I tried your example code, but the `guessedLanguageInformation` is always an empty array. 

My current language config: 
```
'languages' => [
    'en-us' => 'default',
    'de-de' => 'deutsch',
    'es' => 'spanish',
],
```
The `guessedLanguage` currently results in `de-de`

**Comment by pierrestoffe** [comment]
@stephanwergles Could you let me know if it helps to make these two changes please:
1. In Craft's settings, edit your _en-us_ and _de-de_ Sites and set them to _en_ and _de_.
2. In the language redirector config make the same changes.

**Comment by stephanwergles** [comment]
@pierrestoffe unfortunately no change. 
`currentLanguage` equals `en` and `guessedLanguage` equals `de`

But still `guessedLanguageInformation` is an empty array. I also changed the order of my browser's language settings.

**Comment by pierrestoffe** [comment]
@stephanwergles I'm unable to replicate the issue :/
If your project's DB doesn't contain any sensitive info, could you email it to me together with your language-redirector.php file please?

**Comment by stephanwergles** [comment]
@pierrestoffe I've sent a copy of my craft installation to you via email

**Comment by pierrestoffe** [comment]
@stephanwergles Got it, you can update to v3.1.1 which includes the fix.
Feel free to re-open the issue if needed.

**Comment by stephanwergles** [comment]
@pierrestoffe even after updating to v3.1.1 the variable `guessedLanguageInformation` results in an empty array :/

**Comment by pierrestoffe** [comment]
@stephanwergles Do you also have the issue in the simplified Craft install that you sent me? After I installed that version, I enabled the Homepage section in all languages (it was missing) and updated the index.html file with some basic code. I get the right values returned by `guessedLanguageInformation` without having to do anything else.

```twig
{% set guessedLanguage = craft.languageRedirector.getGuessedLanguage() %}
{{ dump(guessedLanguage) }}

{% set guessedLanguageInformation = craft.languageRedirector.getInformationForLanguage(guessedLanguage)|first %}
{{ dump(guessedLanguageInformation) }}
```

![CleanShot 2024-05-03 at 16 05 21](https://github.com/pierrestoffe/craft-language-redirector/assets/1706605/a61df357-199e-49e3-8818-e4011d740853)

I set German as my preferred language, in Firefox
Do you get any other result in that simplified Craft install?

**Comment by stephanwergles** [comment]
@pierrestoffe alright got it...for me homepage section was not enabled for the other language. Now it works fine!

Thank you!
