### ISSUE TITLE
Switch language on a non entry page

### ISSUE THREAD

**Issue by daniellefrapp** [pierrestoffe/craft-language-redirector#3]
This isn't an issue. It's a question. How to you get the language switcher to appear on a page like a blog index that uses a craft route?

**Comment by pierrestoffe** [comment]
@daniellefrapp This case is not covered by this plugin at the moment but I can already think of a way to make it work. I'll add it to the roadmap.

**Comment by pierrestoffe** [comment]
@daniellefrapp A solution was provided in the latest release: https://github.com/pierrestoffe/craft-language-redirector/releases/tag/1.1.1.

From now on you can define a variable in any template (entry-based or not) that tells the plugin which URL to use for each language:
```
{% set languageSwitcherUrls = {
    en: 'https://google.com',
    fr: 'https://google.fr',
    nl: 'https://google.nl',
} %}
```

You can then pass `languageSwitcherUrls` to the `craft.languageSwitcher.getUrls` function, before outputting the language switcher.
```
{% set allLanguages = craft.languageSwitcher.getUrls(languageSwitcherUrls ?? null) %}

<ul>
    {% for item in allLanguages %}
        <li>
            <a href="{{ item.url }}" hreflang="{{ item.id }}" lang="{{ item.id }}" title="{{ 'Switch to ' ~ item.name }}">
                {{ item.nativeName|capitalize }}
                {% if item.id == craft.app.language %}
                    (current)
                {% endif %}
            </a>
        </li>
    {% endfor %}
</ul>
```

**Comment by outline4** [comment]
Hi, I think I am having problems understanding this: 

I have a gallery entry that is called by a route. 
I've put this code into the entry template that is called by the route. 

	{% set languageSwitcherUrls = {
		'de-ch': craft.config.siteUrl.mySite_de,
		'fr-ch': craft.config.siteUrl.mySite_fr
	} %}

In my layouts template I have this code: 

	{% set allLanguages = craft.languageSwitcher.getUrls(languageSwitcherUrls ?? null) %}
	<ul>
		{% for item in allLanguages %}
			<li{% if craft.app.language|lower == item.id %} class="here"{% endif %}>
				<a href="{{ item.url }}" hreflang="{{ item.id }}" lang="{{ item.id }}" title="{{ 'Switch to {language}'|translate({ language: item.name }) }}">
					{% switch item.id|lower %}
						{% case 'de-ch' %}
							DE
						{% case 'fr-ch' %}
							FR
					{% endswitch %}
				</a>
			</li>
		{% endfor %}
	</ul>

OK, the language switcher appears again!  
But: it won't change the current entry to the other language. It will only switch to the url I've specified above. Basically to the root of the site. 

Is there a way to switch languages correctly when the entry is called from a route? 

Is there some sort of a helper function from language switcher? 


Cheers  
Stefan

**Comment by outline4** [comment]
Well, I guess one have to construct the url itself? 

this is what I did: 

	{% set entry = craft.entries.section('gallery').slug(craft.app.request.segments|last).one() %}
	{% set parentEntry = craft.entries.section('pages').uri(craft.app.request.segment(1) ~ "/" ~ craft.app.request.segment(2)).one() %}
	{% set entryDe = craft.entries.id(entry.id).site('mySite_de').one() %}
	{% set entryFr = craft.entries.id(entry.id).site('mySite_fr').one() %}
	{% set parentEntryDe = craft.entries.id(parentEntry.id).site('mySite_de').one() %}
	{% set parentEntryFr = craft.entries.id(parentEntry.id).site('mySite_fr').one() %}
	
	{% set languageSwitcherUrls = {
		'de-ch': craft.config.siteUrl.mySite_de ~ '/' ~ parentEntryDe.uri ~ '/' ~ entryDe.slug,
		'fr-ch': craft.config.siteUrl.mySite_fr ~ '/' ~ parentEntryFr.uri ~ '/' ~ entryFr.slug
	} %}

I find it very cumbersome.  
Do you have a suggestion on making this process more straight forward?

**Comment by pierrestoffe** [comment]
Hi @outline4,

One thing that is certain is that the URLs or the multi-language routes will need to be defined in the templates. As far as I know there is no way of structuring routes per Site in Craft's CP nor in the routes.php file today, so nothing that could potentially make this system even semi-automatic.

I can't find any better way of handling multi-language routes at the moment but I'll spend some time investigating it further this weekend. In any case this would be an interesting [Craft Coding Challenge](https://www.craftcodingchallenge.com)...

**Comment by pierrestoffe** [comment]
My solution, which is still far from ideal but the best I could think off, is the following:

Here is the config of _config/routes.php_, where I define routes per site handle:
```
return [
    'english' => [
        'blogen/<about:\w+>/<id:\d+>' => ['template' => 'blog/_entry']
    ],
    'dutch' => [
        'blognl/<about:\w+>/<id:\d+>' => ['template' => 'blog/_entry']
    ],
    'french' => [
        'blogfr/<about:\w+>/<id:\d+>' => ['template' => 'blog/_entry']
    ],
];
```

And our language switcher in Twig:
```
{% macro route(siteHandle, sites, routes, parent, id) %}
    {% spaceless %}
        {{ alias(sites[siteHandle][0]['baseUrl'] ~ routes[siteHandle]|keys[0]|replace({
            '\<about\:\\w\+\>': parent[siteHandle][0]['uri'],
            "\<id\:\\d\+\>": id
        })) }}
    {% endspaceless %}
{% endmacro %}

{% set routes = craft.businessLogic.getRoutes() %}
{% set sites = craft.app.sites.getAllSites()|group('handle') %}
{% set aboutPage = craft.entries.site(sites|keys).section('aboutPage').all()|group('site.handle') %}

{% set languageSwitcherUrls = {
    en: _self.route('english', sites, routes, aboutPage, id),
    fr: _self.route('french', sites, routes, aboutPage, id),
    nl: _self.route('dutch', sites, routes, aboutPage, id),
} %}
```

The content of the macro would need to be specific to each template of course, but this solution already reduces the need to repeat code for every single Site, and limits the amount of queries made to the database.

Note that `craft.businessLogic.getRoutes` is a Variable that contains the following code:
```
public function getRoutes()
{
    $path = Craft::$app->getPath()->getConfigPath() . DIRECTORY_SEPARATOR . 'routes.php';
    $routes = require $path;
    
    return $routes;
}
```
