### ISSUE TITLE
Without Current Language

### ISSUE THREAD

**Issue by angrotheman** [pierrestoffe/craft-language-redirector#8]
Awesome Plugin, really! But I have one question… Is it possible to add a language switcher WITHOUT the current lang?
In my example I have the option to switch to German if I'm on the German page.

**Comment by angrotheman** [comment]
I got a Solution now

```
<ul>
	{% for item in craft.languageSwitcher.getUrls() if item.id != craft.app.language  %}
	<li>
		<a href="{{ item.url }}">{{ item.nativeName|capitalize }}</a>
	</li>
	 {% endfor %}
</ul>
```

**Comment by pierrestoffe** [comment]
Sorry @angrotheman, I apparently didn't receive a notification for this new issue and only noticed it now.

The solution you found is the one I would have suggested. Just keep in mind that for it to work you will need to use the exact same values in the "Language" field of your Sites' configuration in the CP **and** the keys in the `languages` array in the language-redirector.php config file.
