### ISSUE TITLE
Add a custom Name for Languages

### ISSUE THREAD

**Issue by outline4** [pierrestoffe/craft-language-redirector#9]
Hi, 

I have 3 languages defined:   
de-ch
fr-ch
en

For outputting I can choose between item.id or item.name which would give me the following output:  
de-ch | Deutsch (schweiz)
fr-ch | Französisch (schweiz)
en | Englisch

But Ideally I would like to output the following:  
DE or Deutsch
FR or Französisch
EN or Englisch

Is this somehow possible? 

Cheers
Stefan

**Comment by pierrestoffe** [comment]
Hi @outline4,

Language Redirector uses [a native Craft Class](https://docs.craftcms.com/api/v3/craft-i18n-locale.html) to output the `item.name` and `item.nativeName`. This means that Craft is the one that returns these values. For this reason I sadly have no easy solution that could come from the plugin itself.

This being said, I believe the solution should rather come from your Twig template.
The way I would do it (I actually already used this on a project) is to create a macro that returns the language in the format you prefer based on the `item.id`. The macro would look like this:

```
{% macro getLanguageName(language) %}
    {% switch language %}
        {% case 'de-ch' %}
            {{ 'Deutsch'|translate }}
            
        {% case 'fr-ch' %}
            {{ 'Französisch'|translate }}
            
        {% case 'en' %}
            {{ 'Englisch'|translate }}
            
    {% endswitch %}
{% endmacro %}
```

And you would be able to call it this way:

```
{% import '_macros/macros' as macros %}
{{ macros.getLanguageName(item.id) }}
```

This would return:
- Deutsch
- Französisch
- Englisch

You can then use [Craft's static translations](https://docs.craftcms.com/v3/static-translations.html) mechanism to translate the language names in the other languages of your website.
